### ISSUE TITLE
Not supported for Swift 2.0

### ISSUE THREAD

**Issue by MakeZL** [kostiakoval/Mirror#14] opened 2015-10-03 04:35 UTC
Not supported for Swift 2.0.

Thanks~

**Comment by kostiakoval** [comment] 2015-10-03 10:55
Thanks for feedback, yes I'm working on adding support for swift 2.0

**Comment by kostiakoval** [comment] 2015-10-03 11:02
Closing it as a duplicate of #13

**Closed as completed by kostiakoval** 2015-10-03 11:02 UTC
Labels: duplicate
